### ISSUE TITLE
Perform back from browser, but onConfirm didn't perform back

### ISSUE THREAD

**Issue by tumor800** [ZacharyRSmith/react-router-navigation-prompt#2]
I'm trying to perform action back via browser navigation and `<NavigationPrompt/>` triggered.
But when I click button that have `onClick={onConfirm}`, it not actually back, but it's forwarded.
I expected the program run `history.goBack()`

do you have any solution for this?
could you create props when able to check backward or forward action?

my code:
```
<NavigationPrompt when={(crntLocation, nextLocation) => nextLocation.pathname.startsWith('/movies/schedules')}> 
  {({ isActive, onConfirm, onCancel }) => (
    <Popup
      title="Your Data will be Lost"
      visible={isActive}
      buttons={[<Button primary onClick={onConfirm}>Ok</Button>, <Button outline onClick={onCancel}>Cancel</Button>]}
    >Are you sure you want to leave this page?</Popup>
  )}
</NavigationPrompt>
```

are you do typo in this part?
```

  navigateToNextLocation(cb) {
    let {action, nextLocation} = this.state;
    action = {
      'POP': 'push', // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< this part
      'PUSH': 'push',
      'REPLACE': 'replace'
    }[action || 'PUSH'];
    if (!nextLocation) nextLocation = {pathname: '/'};
    const {history} = this.props;

    this.state.unblock();
    history[action](nextLocation.pathname);
    this.setState({
      ...initState,
      unblock: this.props.history.block(this.block)
    }, cb); // FIXME?  Does history.listen need to be used instead, for async?
  }
```

**Comment by ZacharyRSmith** [comment]
No, that was not a typo.  I originally used pop, but due to issues with that I went to push.

You can read more in my commit message here: https://github.com/ZacharyRSmith/react-router-navigation-prompt/commit/af559d2e1bbd15ae6c50aede8244225fa3272a1a

If user has this in their history:

1. /1/path/ago
2. /2/paths/ago

and right click on back arrow and clicks on /2/paths/ago, then pop() would take them to /1/path/ago instead of /2/paths/ago

**Comment by ZacharyRSmith** [comment]
ie, supporting pop would require a version of `<NavigationPrompt/>` that [requires memory history](https://github.com/ReactTraining/history#properties).  i would like to make that version of `<NavigationPrompt/>`, maybe this weekend?

**Comment by GlebDolzhikov** [comment]
I have i little bit similar issue, i try perform back but onConfirm do nothing in that case.
More then that i get this warn:
Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack

PS: I use hash navigation.

**Comment by piotr-cz** [comment]
I'm using this library inside a PWA.
When user taps on back button, there is a confirmation dialog asking if he/she wants to abandon edits.

Generally in mobile browsers tapping back button rewinds the history to the point when there are no previous entries and then the page tab/ PWA is closed.

The problem with adding new history entry after tapping back button is user is not able to exit the PWA (think close page tab) with back button app.
Instead of history shrinking on confirm there is new entry coming up.

**Comment by ZacharyRSmith** [comment]
ty for reporting this, @piotr-cz .  please make a PR fixing this if you can!

**Comment by piotr-cz** [comment]
I've tried to switch `push` to `goBack` method, [here](https://github.com/ZacharyRSmith/react-router-navigation-prompt/blob/a428d6b1b6e70e7d917f684e510adf7b91cb34d2/src/index.js#L110)  as a revert of https://github.com/ZacharyRSmith/react-router-navigation-prompt/commit/af559d2e1bbd15ae6c50aede8244225fa3272a1a  but that didn't work

I'll work on it later

**Comment by piotr-cz** [comment]
Can you elaborate on your commit message _We cannot know the correct history entry to pop to without using memory history_ ?

**Comment by piotr-cz** [comment]
Everybody, please test and comment on https://github.com/ZacharyRSmith/react-router-navigation-prompt/pull/30

**Comment by piotr-cz** [comment]
Back button should work now (as  some of us expect it to), when using new `allowGoBack={true}` option.
For implementation details see #39, for option details see README.md.
